In [1]:
import numpy as np
import pandas as pd
from functools import reduce

In [2]:
file1 = "SUBGRID_DATA_IMAGEBASED_FOLIAGE_DELTA_100.txt"
file2 = "SUBGRID_DATA_IMAGEBASED_FOLIAGE_DELTA_101.txt"
file3 = "SUBGRID_DATA_IMAGEBASED_FOLIAGE_DELTA_102.txt"
file4 = "SUBGRID_DATA_IMAGEBASED_FOLIAGE_DELTA_102+OUTDATED.txt"
file5 = "SUBGRID_DATA_IMAGEBASED_FOLIAGE_DELTA_103.txt"

In [3]:
df1 = pd.read_csv(file1, sep="\t")
df2 = pd.read_csv(file2, sep="\t")
df3 = pd.read_csv(file3, sep="\t")
df4 = pd.read_csv(file4, sep="\t")
df5 = pd.read_csv(file5, sep="\t")

In [4]:
df1.head()

,IMAGE_NAME,PT_LAT,PT_LON,FOLIAGE_PROB_100,FOLIAGE_PROB_NEW,FOLIAGE_PROB_delta_100
0,Delhi.0.tif,28.879125,76.842739,1.944742e-10,0.113549,-0.113549
1,Delhi.0.tif,28.879125,76.843188,3.079320e-10,0.085690,-0.085690
2,Delhi.0.tif,28.879125,76.843637,1.064966e-10,0.045789,-0.045789
3,Delhi.0.tif,28.879125,76.844086,3.271573e-10,0.094263,-0.094263
4,Delhi.0.tif,28.879125,76.844536,1.342774e-10,0.056119,-0.056119

In [5]:
df2.head()

,IMAGE_NAME,PT_LAT,PT_LON,FOLIAGE_PROB_101,FOLIAGE_PROB_NEW,FOLIAGE_PROB_delta_101
0,Delhi.0.tif,28.879125,76.842739,3.303336e-08,0.113549,-0.113549
1,Delhi.0.tif,28.879125,76.843188,4.527136e-08,0.085690,-0.085690
2,Delhi.0.tif,28.879125,76.843637,4.043867e-08,0.045789,-0.045789
3,Delhi.0.tif,28.879125,76.844086,5.755490e-08,0.094263,-0.094263
4,Delhi.0.tif,28.879125,76.844536,2.142281e-08,0.056119,-0.056119

In [6]:
data_frames = [df1,df2,df3,df4,df5]

In [7]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['IMAGE_NAME', 'PT_LAT', 'PT_LON', 'FOLIAGE_PROB_NEW'],
                                            how='outer'), data_frames)
df_merged.head()

,IMAGE_NAME,PT_LAT,PT_LON,FOLIAGE_PROB_100,FOLIAGE_PROB_NEW,FOLIAGE_PROB_delta_100,FOLIAGE_PROB_101,FOLIAGE_PROB_delta_101,FOLIAGE_PROB_102,FOLIAGE_PROB_delta_102,FOLIAGE_PROB_102+OUTDATED,FOLIAGE_PROB_delta_102+OUTDATED,FOLIAGE_PROB_103,FOLIAGE_PROB_delta_103
0,Delhi.0.tif,28.879125,76.842739,1.944742e-10,0.113549,-0.113549,3.303336e-08,-0.113549,0.055886,-0.057664,0.006765,-0.106784,0.011904,-0.101646
1,Delhi.0.tif,28.879125,76.843188,3.079320e-10,0.085690,-0.085690,4.527136e-08,-0.085690,0.004419,-0.081271,0.000890,-0.084800,0.002166,-0.083524
2,Delhi.0.tif,28.879125,76.843637,1.064966e-10,0.045789,-0.045789,4.043867e-08,-0.045789,0.006514,-0.039274,0.000880,-0.044908,0.000955,-0.044833
3,Delhi.0.tif,28.879125,76.844086,3.271573e-10,0.094263,-0.094263,5.755490e-08,-0.094263,0.012977,-0.081286,0.002570,-0.091693,0.005035,-0.089228
4,Delhi.0.tif,28.879125,76.844536,1.342774e-10,0.056119,-0.056119,2.142281e-08,-0.056119,0.005529,-0.050591,0.000710,-0.055410,0.002008,-0.054111

In [9]:
headers_delta = list(df_merged.columns.values)
print(headers_delta)

['IMAGE_NAME', 'PT_LAT', 'PT_LON', 'FOLIAGE_PROB_100', 'FOLIAGE_PROB_NEW', 'FOLIAGE_PROB_delta_100', 'FOLIAGE_PROB_101', 'FOLIAGE_PROB_delta_101', 'FOLIAGE_PROB_102', 'FOLIAGE_PROB_delta_102', 'FOLIAGE_PROB_102+OUTDATED', 'FOLIAGE_PROB_delta_102+OUTDATED', 'FOLIAGE_PROB_103', 'FOLIAGE_PROB_delta_103']

In [10]:
df_delta = df_merged[['IMAGE_NAME', 
                'PT_LAT', 
                'PT_LON', 
                'FOLIAGE_PROB_NEW', 
                'FOLIAGE_PROB_100', 
                'FOLIAGE_PROB_101',
                'FOLIAGE_PROB_102',
                'FOLIAGE_PROB_102+OUTDATED',
                'FOLIAGE_PROB_103',
                'FOLIAGE_PROB_delta_100',
                'FOLIAGE_PROB_delta_101',
                'FOLIAGE_PROB_delta_102',
                'FOLIAGE_PROB_delta_102+OUTDATED',
                'FOLIAGE_PROB_delta_103']]
df_delta.head()

,IMAGE_NAME,PT_LAT,PT_LON,FOLIAGE_PROB_NEW,FOLIAGE_PROB_100,FOLIAGE_PROB_101,FOLIAGE_PROB_102,FOLIAGE_PROB_102+OUTDATED,FOLIAGE_PROB_103,FOLIAGE_PROB_delta_100,FOLIAGE_PROB_delta_101,FOLIAGE_PROB_delta_102,FOLIAGE_PROB_delta_102+OUTDATED,FOLIAGE_PROB_delta_103
0,Delhi.0.tif,28.879125,76.842739,0.113549,1.944742e-10,3.303336e-08,0.055886,0.006765,0.011904,-0.113549,-0.113549,-0.057664,-0.106784,-0.101646
1,Delhi.0.tif,28.879125,76.843188,0.085690,3.079320e-10,4.527136e-08,0.004419,0.000890,0.002166,-0.085690,-0.085690,-0.081271,-0.084800,-0.083524
2,Delhi.0.tif,28.879125,76.843637,0.045789,1.064966e-10,4.043867e-08,0.006514,0.000880,0.000955,-0.045789,-0.045789,-0.039274,-0.044908,-0.044833
3,Delhi.0.tif,28.879125,76.844086,0.094263,3.271573e-10,5.755490e-08,0.012977,0.002570,0.005035,-0.094263,-0.094263,-0.081286,-0.091693,-0.089228
4,Delhi.0.tif,28.879125,76.844536,0.056119,1.342774e-10,2.142281e-08,0.005529,0.000710,0.002008,-0.056119,-0.056119,-0.050591,-0.055410,-0.054111

In [ ]:
"""
df_delta = df_delta.rename(columns={'BUILD_PROB_NEW_x': 'BUILD_PROB_NEW', 
                                    'BUILD_PROB_NEW_y': 'BUILD_PROB_NEW_100', 
                                    'BUILD_PROB_delta_x': 'BUILD_PROB_delta', 
                                    'BUILD_PROB_delta_y': 'BUILD_PROB_delta_100'})
df_delta.head()
"""

In [ ]:
df_delta.to_csv('SUBGRID_DATA_IMAGEBASED_FOLIAGE_DELTA_103_EXT.txt', sep='\t', index=False)