In [1]:
import numpy as np
import pandas as pd

In [6]:
file1 = "SUBGRID_DATA_IMAGEBASED_DELTA_100.txt"
file2 = "SUBGRID_DATA_IMAGEBASED_100.txt"

In [7]:
df1 = pd.read_csv(file1, sep="\t")
df2 = pd.read_csv(file2, sep="\t")

In [8]:
df1.head()

,IMAGE_NAME,PT_LAT,PT_LON,BUILD_PROB_OLD,BUILD_PROB_NEW,BUILD_PROB_NEW_100,BUILD_PROB_delta,BUILD_PROB_delta_100
0,Delhi.0.tif,28.879125,76.842739,0.118640,0.244506,0.030370,0.125866,-0.088270
1,Delhi.0.tif,28.879125,76.843188,0.109928,0.124218,0.038626,0.014290,-0.071302
2,Delhi.0.tif,28.879125,76.843637,0.126650,0.337704,0.296383,0.211054,0.169733
3,Delhi.0.tif,28.879125,76.844086,0.133599,0.267742,0.077171,0.134143,-0.056428
4,Delhi.0.tif,28.879125,76.844536,0.112802,0.315225,0.140277,0.202424,0.027476

In [9]:
df2.head()

   Unnamed: 0   IMAGE_NAME     PT_LAT     PT_LON  BUILD_PROB
0           0  Delhi.0.tif  28.879125  76.842739    0.035791
1           1  Delhi.0.tif  28.879125  76.843188    0.059589
2           2  Delhi.0.tif  28.879125  76.843637    0.116285
3           3  Delhi.0.tif  28.879125  76.844086    0.080166
4           4  Delhi.0.tif  28.879125  76.844536    0.084771

In [10]:
df = pd.merge(df1, df2, on=['IMAGE_NAME', 'PT_LAT', 'PT_LON', 'BUILD_PROB_OLD'], 
              how='outer', indicator=True)
df.head()

,IMAGE_NAME,PT_LAT,PT_LON,BUILD_PROB_OLD,BUILD_PROB_NEW,BUILD_PROB_NEW_100,BUILD_PROB_delta,BUILD_PROB_delta_100,Unnamed: 0,BUILD_PROB,_merge
0,Delhi.0.tif,28.879125,76.842739,0.118640,0.244506,0.030370,0.125866,-0.088270,0.0,0.035791,both
1,Delhi.0.tif,28.879125,76.843188,0.109928,0.124218,0.038626,0.014290,-0.071302,1.0,0.059589,both
2,Delhi.0.tif,28.879125,76.843637,0.126650,0.337704,0.296383,0.211054,0.169733,2.0,0.116285,both
3,Delhi.0.tif,28.879125,76.844086,0.133599,0.267742,0.077171,0.134143,-0.056428,3.0,0.080166,both
4,Delhi.0.tif,28.879125,76.844536,0.112802,0.315225,0.140277,0.202424,0.027476,4.0,0.084771,both

In [11]:
headers_delta = list(df.columns.values)
print(headers_delta)

['IMAGE_NAME', 'PT_LAT', 'PT_LON', 'BUILD_PROB_OLD', 'BUILD_PROB_NEW', 'BUILD_PROB_NEW_100', 'BUILD_PROB_delta', 'BUILD_PROB_delta_100', 'Unnamed: 0', 'BUILD_PROB', '_merge']

In [8]:
df_delta = df[['IMAGE_NAME', 
                'PT_LAT', 
                'PT_LON', 
                'BUILD_PROB_OLD', 
                'BUILD_PROB_NEW_x', 
                'BUILD_PROB_NEW_y', 
                'BUILD_PROB_delta_x', 
                'BUILD_PROB_delta_y']]
#df_delta.head()

In [9]:
df_delta = df_delta.rename(columns={'BUILD_PROB_NEW_x': 'BUILD_PROB_NEW', 
                                    'BUILD_PROB_NEW_y': 'BUILD_PROB_NEW_100', 
                                    'BUILD_PROB_delta_x': 'BUILD_PROB_delta', 
                                    'BUILD_PROB_delta_y': 'BUILD_PROB_delta_100'})
df_delta.head()

,IMAGE_NAME,PT_LAT,PT_LON,BUILD_PROB_OLD,BUILD_PROB_NEW,BUILD_PROB_NEW_100,BUILD_PROB_delta,BUILD_PROB_delta_100
0,Delhi.0.tif,28.879125,76.842739,0.118640,0.244506,0.030370,0.125866,-0.088270
1,Delhi.0.tif,28.879125,76.843188,0.109928,0.124218,0.038626,0.014290,-0.071302
2,Delhi.0.tif,28.879125,76.843637,0.126650,0.337704,0.296383,0.211054,0.169733
3,Delhi.0.tif,28.879125,76.844086,0.133599,0.267742,0.077171,0.134143,-0.056428
4,Delhi.0.tif,28.879125,76.844536,0.112802,0.315225,0.140277,0.202424,0.027476

In [10]:
df_delta.to_csv('SUBGRID_DATA_IMAGEBASED_DELTA_100_EXT', sep='\t', index=False)