In [1]:
import numpy as np
import pandas as pd

In [2]:
file1 = "SUBGRID_DATA_IMAGEBASED_FOLIAGE_NEW.txt"
file2 = "SUBGRID_DATA_IMAGEBASED_FOLIAGE_103.txt"

In [3]:
df1 = pd.read_csv(file1, sep="\t")
df2 = pd.read_csv(file2, sep="\t")

In [4]:
df1.head()

   Unnamed: 0   IMAGE_NAME     PT_LAT     PT_LON  FOLIAGE_PROB
0           0  Delhi.0.tif  28.879125  76.842739      0.113549
1           1  Delhi.0.tif  28.879125  76.843188      0.085690
2           2  Delhi.0.tif  28.879125  76.843637      0.045789
3           3  Delhi.0.tif  28.879125  76.844086      0.094263
4           4  Delhi.0.tif  28.879125  76.844536      0.056119

In [5]:
df2.head()

   Unnamed: 0   IMAGE_NAME     PT_LAT     PT_LON  FOLIAGE_PROB
0           0  Delhi.0.tif  28.879125  76.842739      0.011904
1           1  Delhi.0.tif  28.879125  76.843188      0.002166
2           2  Delhi.0.tif  28.879125  76.843637      0.000955
3           3  Delhi.0.tif  28.879125  76.844086      0.005035
4           4  Delhi.0.tif  28.879125  76.844536      0.002008

In [6]:
headers_delta = list(df2.columns.values)
headers_delta = headers_delta[1:]
print(headers_delta)

['IMAGE_NAME', 'PT_LAT', 'PT_LON', 'FOLIAGE_PROB']

In [7]:
headers_delta[-1] = 'FOLIAGE_PROB_103'
headers_delta.append('FOLIAGE_PROB_NEW')
headers_delta.append('FOLIAGE_PROB_delta_103')
print(headers_delta)

['IMAGE_NAME', 'PT_LAT', 'PT_LON', 'FOLIAGE_PROB_103', 'FOLIAGE_PROB_NEW', 'FOLIAGE_PROB_delta_103']

In [8]:
df = pd.merge(df1, df2, on=['Unnamed: 0', 'IMAGE_NAME', 'PT_LAT', 'PT_LON'], how='outer', indicator=True)
df.head()

,Unnamed: 0,IMAGE_NAME,PT_LAT,PT_LON,FOLIAGE_PROB_x,FOLIAGE_PROB_y,_merge
0,0,Delhi.0.tif,28.879125,76.842739,0.113549,0.011904,both
1,1,Delhi.0.tif,28.879125,76.843188,0.085690,0.002166,both
2,2,Delhi.0.tif,28.879125,76.843637,0.045789,0.000955,both
3,3,Delhi.0.tif,28.879125,76.844086,0.094263,0.005035,both
4,4,Delhi.0.tif,28.879125,76.844536,0.056119,0.002008,both

In [9]:
#df.set_index(['PT_LAT', 'PT_LON'])

In [10]:
list_delta = []
for i in df['Unnamed: 0'].values:
    FOLIAGE_PROB_delta = df['FOLIAGE_PROB_y'][i] - df['FOLIAGE_PROB_x'][i]
    list_delta.append([df['IMAGE_NAME'][i], df['PT_LAT'][i], df['PT_LON'][i], df['FOLIAGE_PROB_y'][i], df['FOLIAGE_PROB_x'][i], FOLIAGE_PROB_delta])

In [11]:
df_delta = pd.DataFrame(list_delta, columns=headers_delta)

In [12]:
df_delta.head()

,IMAGE_NAME,PT_LAT,PT_LON,FOLIAGE_PROB_103,FOLIAGE_PROB_NEW,FOLIAGE_PROB_delta_103
0,Delhi.0.tif,28.879125,76.842739,0.011904,0.113549,-0.101646
1,Delhi.0.tif,28.879125,76.843188,0.002166,0.085690,-0.083524
2,Delhi.0.tif,28.879125,76.843637,0.000955,0.045789,-0.044833
3,Delhi.0.tif,28.879125,76.844086,0.005035,0.094263,-0.089228
4,Delhi.0.tif,28.879125,76.844536,0.002008,0.056119,-0.054111

In [13]:
df_delta.to_csv('SUBGRID_DATA_IMAGEBASED_FOLIAGE_DELTA_103.txt', sep='\t', index=False)